package it.polimi.ingsw.is25am28.GameModelv2;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import it.polimi.ingsw.is25am28.Player.PlayerColor;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class GameModelTest {
    private GameModel model;

    @BeforeEach
    public void init() {
        // Init the gameModel
        model = new GameModel();
    }

    @Test
    public void test_leader_connect_to_the_game_and_set_the_configuration() throws JsonProcessingException {
        // Test that the initial state is the createGameState
        assertInstanceOf(CreateGameState.class, model.getCurrentState());

        // Test the state generated by the state
        ObjectMapper mapper = new ObjectMapper();
        String json = mapper.writeValueAsString(model.generateState());
        String expectedState = "{\"availableColors\":[\"GREEN\",\"RED\",\"BLUE\",\"YELLOW\"],\"usedNicknames\":[],\"stateName\":\"CreateGameState\"}";
        assertEquals(expectedState, json);

        model.gameConfig("Player 1", PlayerColor.RED, 2, 4);

        assertEquals(2, model.getGameLevel());
        assertEquals(4, model.getNumPlayers());
        assertEquals(1, model.getPlayers().size());
        assertEquals(3, model.getAvailableColors().size());

        // Check if the gameState has changed
        assertInstanceOf(WaitPlayersState.class, model.getCurrentState());
    }

}